#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm exec flh --tscheck --eslint --only-changes --fix
pnpm exec flh --prettier --only-changes --fix

# npm run fix:prettier -- --cache
# npm run test:lint
# git add --update
